#!/usr/bin/env node

/**
 * PR body generator for automated data updates.
 * Creates structured Markdown with diffs, source links, and review checklists.
 */

import { writeFileSync } from "fs";

/**
 * @typedef {object} SourceReport
 * @property {string} sourceName - Human-readable name
 * @property {string} dataFile - Path to the data file
 * @property {string[]} sourceUrls - URLs that were scraped
 * @property {"updated" | "unchanged" | "failed"} status
 * @property {Array<{ field: string, message: string }>} changes
 * @property {Array<{ level: string, message: string }>} warnings
 * @property {string} [rawContent] - Extracted text (for audit trail)
 * @property {string} [error] - Error message if failed
 */

/**
 * Generate a PR body from source reports.
 *
 * @param {SourceReport[]} reports
 * @returns {string} Markdown PR body
 */
export function generatePrBody(reports) {
  const updated = reports.filter((r) => r.status === "updated");
  const unchanged = reports.filter((r) => r.status === "unchanged");
  const failed = reports.filter((r) => r.status === "failed");

  const allWarnings = reports.flatMap((r) => r.warnings || []);
  const hasWarnings = allWarnings.length > 0;

  let body = `## Automated Data Update\n\n`;

  // Summary
  body += `**${updated.length}** source(s) updated`;
  if (unchanged.length > 0) body += ` · **${unchanged.length}** unchanged`;
  if (failed.length > 0) body += ` · **${failed.length}** failed`;
  body += `\n\n`;

  // Warnings banner
  if (hasWarnings) {
    body += `### ⚠️ Warnings\n\n`;
    for (const w of allWarnings) {
      body += `- ${w.level === "error" ? "🔴" : "🟡"} ${w.message}\n`;
    }
    body += `\n`;
  }

  // Changes detail
  if (updated.length > 0) {
    body += `### Changes\n\n`;
    for (const report of updated) {
      body += `#### ${report.sourceName}\n`;
      body += `**File:** \`${report.dataFile}\`\n\n`;

      if (report.changes.length > 0) {
        body += `| Field | Change |\n|-------|--------|\n`;
        for (const change of report.changes) {
          body += `| ${change.field} | ${change.message} |\n`;
        }
        body += `\n`;
      }

      // Source URLs
      body += `**Sources:**\n`;
      for (const url of report.sourceUrls) {
        body += `- ${url}\n`;
      }
      body += `\n`;
    }
  }

  // Failed sources
  if (failed.length > 0) {
    body += `### ❌ Failed Sources\n\n`;
    for (const report of failed) {
      body += `- **${report.sourceName}**: ${report.error || "Unknown error"}\n`;
      for (const url of report.sourceUrls) {
        body += `  - ${url}\n`;
      }
    }
    body += `\n`;
  }

  // Audit trail (collapsible raw content)
  const reportsWithContent = reports.filter(
    (r) => r.rawContent && r.status === "updated"
  );
  if (reportsWithContent.length > 0) {
    body += `### Audit Trail\n\n`;
    for (const report of reportsWithContent) {
      body += `<details>\n<summary>Raw extracted content: ${report.sourceName}</summary>\n\n`;
      body += `\`\`\`\n${report.rawContent.slice(0, 5000)}\n\`\`\`\n\n`;
      body += `</details>\n\n`;
    }
  }

  // Review checklist
  body += `### Review Checklist\n\n`;
  body += `- [ ] Verify changed values against source URLs above\n`;
  body += `- [ ] Check that no data was incorrectly removed\n`;
  body += `- [ ] Confirm FAQs and metadata are preserved\n`;
  body += `- [ ] Run \`npm run build\` to verify static export\n`;
  body += `\n`;

  body += `---\n🤖 Generated by PesoHub Data Updater\n`;

  return body;
}

/**
 * Write PR body to a file for GitHub Actions to pick up.
 *
 * @param {SourceReport[]} reports
 * @param {string} outputPath
 */
export function writePrBody(reports, outputPath = "/tmp/pr-body.md") {
  const body = generatePrBody(reports);
  writeFileSync(outputPath, body, "utf-8");
  console.log(`PR body written to ${outputPath}`);
  return body;
}
