/**
 * PesoHub Email API — Express Server (DigitalOcean)
 *
 * Handles two endpoints:
 *   POST /contact    — Contact form submissions (sends to hello@pesohub.ph)
 *   POST /calculator — Calculator results email (sends to user's email)
 *
 * Environment variables:
 *   RESEND_API_KEY   — Resend API key
 *   FROM_EMAIL       — Sender email (default: noreply@pesohub.ph)
 *   TO_EMAIL         — Contact form recipient (default: hello@pesohub.ph)
 *   ALLOWED_ORIGIN   — CORS origin (default: https://pesohub.ph)
 *   PORT             — Server port (default: 3001)
 */

import express from "express";
import cors from "cors";

const app = express();
const PORT = process.env.PORT || 3001;
const FROM_EMAIL = process.env.FROM_EMAIL || "noreply@pesohub.ph";
const TO_EMAIL = process.env.TO_EMAIL || "hello@pesohub.ph";
const ALLOWED_ORIGIN = process.env.ALLOWED_ORIGIN || "https://pesohub.ph";
const RESEND_API_KEY = process.env.RESEND_API_KEY;

if (!RESEND_API_KEY) {
  console.error("❌ RESEND_API_KEY environment variable is required");
  process.exit(1);
}

// CORS
const allowedOrigins = [
  ALLOWED_ORIGIN,
  "https://pesohub.pages.dev",
  "http://localhost:3000",
];

// Allow Vercel preview deployments (*.vercel.app)
function isAllowedOrigin(origin) {
  if (!origin) return true;
  if (allowedOrigins.includes(origin)) return true;
  if (/^https:\/\/[\w-]+-[\w-]+\.vercel\.app$/.test(origin)) return true;
  return false;
}

app.use(
  cors({
    origin: (origin, callback) => {
      if (isAllowedOrigin(origin)) {
        callback(null, true);
      } else {
        callback(null, ALLOWED_ORIGIN);
      }
    },
    methods: ["POST", "OPTIONS"],
    allowedHeaders: ["Content-Type"],
    maxAge: 86400,
  })
);

app.use(express.json());

// ── Helpers ──────────────────────────────────────────────────────

function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

async function sendEmail(from, to, subject, htmlBody) {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: `PesoHub <${from}>`,
      to: [to],
      subject,
      html: htmlBody,
    }),
  });
  return res;
}

const SUBJECT_LABELS = {
  general: "General Inquiry",
  bug: "Bug Report",
  suggestion: "Feature Suggestion",
  data: "Data Correction",
  partnership: "Partnership / Advertising",
  other: "Other",
};

function buildContactEmail({ name, email, subject, message }) {
  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 560px; margin: 0 auto; padding: 24px;">
      <h2 style="color: #0f172a; font-size: 18px; margin: 0 0 16px;">New Contact Form Submission</h2>
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <tr>
          <td style="padding: 8px 12px; font-weight: 600; color: #64748b; vertical-align: top; width: 100px;">Name</td>
          <td style="padding: 8px 12px; color: #0f172a;">${escapeHtml(name)}</td>
        </tr>
        <tr>
          <td style="padding: 8px 12px; font-weight: 600; color: #64748b; vertical-align: top;">Email</td>
          <td style="padding: 8px 12px; color: #0f172a;"><a href="mailto:${escapeHtml(email)}" style="color: #093CB5;">${escapeHtml(email)}</a></td>
        </tr>
        <tr>
          <td style="padding: 8px 12px; font-weight: 600; color: #64748b; vertical-align: top;">Subject</td>
          <td style="padding: 8px 12px; color: #0f172a;">${escapeHtml(SUBJECT_LABELS[subject] || subject)}</td>
        </tr>
        <tr>
          <td style="padding: 8px 12px; font-weight: 600; color: #64748b; vertical-align: top;">Message</td>
          <td style="padding: 8px 12px; color: #0f172a; white-space: pre-wrap;">${escapeHtml(message)}</td>
        </tr>
      </table>
      <p style="margin-top: 24px; font-size: 12px; color: #94a3b8;">Sent from pesohub.ph contact form</p>
    </div>
  `;
}

function buildCalculatorEmail({ email, calculatorType, results }) {
  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 560px; margin: 0 auto; padding: 24px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h2 style="color: #0f172a; font-size: 20px; margin: 0;">Your PesoHub Calculation Results</h2>
        <p style="color: #64748b; font-size: 13px; margin: 8px 0 0;">${escapeHtml(calculatorType)}</p>
      </div>
      <div style="background: #f8fafc; border-radius: 8px; padding: 20px; font-size: 14px; color: #0f172a; white-space: pre-wrap; line-height: 1.6;">${escapeHtml(results)}</div>
      <p style="margin-top: 24px; font-size: 12px; color: #94a3b8; text-align: center;">
        Generated by <a href="https://pesohub.ph" style="color: #093CB5; text-decoration: none;">PesoHub</a> — Practical Money Tools for Filipinos
      </p>
      <p style="font-size: 11px; color: #cbd5e1; text-align: center; margin-top: 8px;">
        This is for informational purposes only and does not constitute financial advice.
      </p>
    </div>
  `;
}

// ── Routes ───────────────────────────────────────────────────────

app.post("/contact", async (req, res) => {
  try {
    const { name, email, subject, message } = req.body;

    if (!name || !email || !subject || !message) {
      return res.status(400).json({ error: "All fields are required" });
    }

    const emailRes = await sendEmail(
      FROM_EMAIL,
      TO_EMAIL,
      `[PesoHub] ${SUBJECT_LABELS[subject] || subject} from ${name}`,
      buildContactEmail({ name, email, subject, message })
    );

    if (!emailRes.ok) {
      const errText = await emailRes.text();
      console.error("Resend error:", errText);
      return res.status(502).json({ error: "Failed to send email" });
    }

    return res.json({ success: true });
  } catch (err) {
    console.error("Contact error:", err);
    return res.status(400).json({ error: "Invalid request" });
  }
});

app.post("/calculator", async (req, res) => {
  try {
    const { email, calculatorType, results } = req.body;

    if (!email || !calculatorType || !results) {
      return res.status(400).json({ error: "All fields are required" });
    }

    const emailRes = await sendEmail(
      FROM_EMAIL,
      email,
      `Your ${calculatorType} Results — PesoHub`,
      buildCalculatorEmail({ email, calculatorType, results })
    );

    if (!emailRes.ok) {
      const errText = await emailRes.text();
      console.error("Resend error:", errText);
      return res.status(502).json({ error: "Failed to send email" });
    }

    return res.json({ success: true });
  } catch (err) {
    console.error("Calculator error:", err);
    return res.status(400).json({ error: "Invalid request" });
  }
});

// Health check
app.get("/health", (req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// ── Start ────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`✅ PesoHub Email API running on port ${PORT}`);
});
