/**
 * Generates PR body markdown for blog post PRs.
 */

import { writeFileSync } from "fs";

/**
 * Generate and write a PR body for a blog post.
 *
 * @param {object} options
 * @param {string} options.slug - Post slug
 * @param {string} options.title - Post title
 * @param {string} options.keyword - Target keyword
 * @param {object} options.review - Review result from reviewer agent
 * @param {number} options.wordCount - Approximate word count
 */
export function writePrBody({ slug, title, keyword, review, wordCount }) {
  const verdict = review.approved
    ? "✅ Publish"
    : `⚠️ ${(review.publishRecommendation ?? "revise").toUpperCase()}`;
  const body = `## Blog Post: ${title}

**Slug:** \`${slug}\`
**Target keyword:** \`${keyword}\`
**Word count:** ~${wordCount}
**Evaluator:** ${review.passed ?? "?"}/${review.total ?? 10} criteria pass · critical ${review.criticalPassed ? "OK" : "FAIL"}
**Status:** ${verdict}

### Review Summary

${review.issues.length > 0 ? `**Issues:**\n${review.issues.map((i) => `- ${i}`).join("\n")}` : "No issues found."}

${review.suggestions.length > 0 ? `**Suggestions:**\n${review.suggestions.map((s) => `- ${s}`).join("\n")}` : ""}

### Files Changed

- \`src/data/blog/${slug}.ts\` — Blog post data
- \`src/data/blog/index.ts\` — Registry entry added
- \`src/app/blog/[slug]/page.tsx\` — Module mapping added

### Checklist

- [ ] Content reviewed for accuracy
- [ ] Links to PesoHub pages verified
- [ ] Meta title and description look good
- [ ] FAQs are helpful and accurate
- [ ] Disclaimer is appropriate

---
🤖 Generated by PesoHub Blog Agent
`;

  writeFileSync("/tmp/pr-body.md", body, "utf-8");
  writeFileSync("/tmp/blog-slug.txt", slug, "utf-8");
  console.log(`  📋 PR body written to /tmp/pr-body.md`);
}

/**
 * PR body for a non-post content action (update/merge/hold/reject). The
 * generated package is a Markdown file for a human to apply; no live page is
 * auto-edited.
 *
 * @param {{slug: string, action: string, keyword: string, file: string, markdown: string}} options
 */
export function writePackagePrBody({ slug, action, keyword, file, markdown, targetPage, review }) {
  const rel = file.replace(/^.*\/(scripts\/blog-agent\/output\/.*)$/, "$1");
  const targetLine = targetPage ? `\n**Target page:** \`${targetPage}\`` : "";

  let gradeSection = "";
  if (review) {
    const verdict = review.approved
      ? "✅ APPLY"
      : `⚠️ ${String(review.publishRecommendation || "review").toUpperCase()}`;
    const pct = Math.round((review.passRate ?? 0) * 100);
    const issues = (review.issues ?? []).length
      ? `\n\n**Must-fix before applying:**\n${review.issues.map((i) => `- ${i}`).join("\n")}`
      : "";
    const fixes = (review.suggestions ?? []).length
      ? `\n\n**Suggested improvements:**\n${review.suggestions.map((s) => `- ${s}`).join("\n")}`
      : "";
    gradeSection = `

### Package grade: ${verdict}

- Criteria passed: ${review.passed ?? "?"}/${review.total ?? "?"} (${pct}%)
- Critical criteria: ${review.criticalPassed ? "OK" : "FAIL — " + (review.failedCriteria ?? []).join(", ")}${issues}${fixes}`;
  }

  const body = `## Content action: \`${action}\`

**Keyword:** \`${keyword}\`${targetLine}
**Action package:** \`${rel}\`

This is a **human-apply** package — the keyword-opportunity agent recommended \`${action}\`, not a new post, so no live page was auto-edited. Review the package and apply it manually.${gradeSection}

---

${markdown}

---
🤖 Generated by PesoHub Blog Agent
`;

  writeFileSync("/tmp/pr-body.md", body, "utf-8");
  writeFileSync("/tmp/blog-slug.txt", slug, "utf-8");
  console.log(`  📋 Action-package PR body written to /tmp/pr-body.md`);
}
