/**
 * Generates PR body markdown for blog post PRs.
 */

import { writeFileSync } from "fs";

/**
 * Generate and write a PR body for a blog post.
 *
 * @param {object} options
 * @param {string} options.slug - Post slug
 * @param {string} options.title - Post title
 * @param {string} options.keyword - Target keyword
 * @param {object} options.review - Review result from reviewer agent
 * @param {number} options.wordCount - Approximate word count
 */
export function writePrBody({ slug, title, keyword, review, wordCount }) {
  const body = `## Blog Post: ${title}

**Slug:** \`${slug}\`
**Target keyword:** \`${keyword}\`
**Word count:** ~${wordCount}
**Review score:** ${review.score}/100
**Status:** ${review.approved ? "✅ Approved" : "❌ Needs revision"}

### Review Summary

${review.issues.length > 0 ? `**Issues:**\n${review.issues.map((i) => `- ${i}`).join("\n")}` : "No issues found."}

${review.suggestions.length > 0 ? `**Suggestions:**\n${review.suggestions.map((s) => `- ${s}`).join("\n")}` : ""}

### Files Changed

- \`src/data/blog/${slug}.ts\` — Blog post data
- \`src/data/blog/index.ts\` — Registry entry added
- \`src/app/blog/[slug]/page.tsx\` — Module mapping added

### Checklist

- [ ] Content reviewed for accuracy
- [ ] Links to PesoHub pages verified
- [ ] Meta title and description look good
- [ ] FAQs are helpful and accurate
- [ ] Disclaimer is appropriate

---
🤖 Generated by PesoHub Blog Agent
`;

  writeFileSync("/tmp/pr-body.md", body, "utf-8");
  writeFileSync("/tmp/blog-slug.txt", slug, "utf-8");
  console.log(`  📋 PR body written to /tmp/pr-body.md`);
}
